parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: footballpodcasts_symfony
    database_user: root
    database_password: root1
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: e9cdb3e9446a655a77db979701279f0c792ce137
    database_path: null
